// GROOVE — The Journalist (Context Synthesis Engine)
// FSL-1.1-Apache-2.0 — see LICENSE

import { readFileSync, writeFileSync, existsSync, mkdirSync, statSync } from 'fs';
import { resolve } from 'path';
import { execFile, spawn as cpSpawn } from 'child_process';
import { getProvider, getInstalledProviders, resolveProviderCommand } from './providers/index.js';

const DEFAULT_INTERVAL = 300_000; // 5 minutes (safety-net fallback; event-driven triggers handle the normal case)
const MAX_LOG_CHARS = 100_000; // ~25k tokens budget for synthesis input (captures 80-90% of recent activity)
const DEBOUNCE_MS = 10_000; // requestSynthesis debounce window

export class Journalist {
  constructor(daemon) {
    this.daemon = daemon;
    this.interval = null;
    this.cycleCount = 0;
    this.lastCycleAt = null;
    this.lastLogSizes = {}; // agentId -> last known log byte size
    this.synthesizing = false;
    this.lastSynthesis = null; // last synthesis result text
    this.history = []; // recent synthesis summaries
    this._debounceTimer = null;
    this._debounceReason = null;
    this._forceNextCycle = false;
  }

  start(intervalMs = DEFAULT_INTERVAL) {
    if (this.interval) return;

    // Run first cycle immediately, then on interval
    this.cycle();
    this.interval = setInterval(() => this.cycle(), intervalMs);
  }

  /**
   * Seed the journalist with the init map generated by the indexer.
   * Sets it as the initial synthesis so agents read it immediately.
   */
  seedFromInitMap() {
    const mapPath = resolve(this.daemon.projectDir, 'GROOVE_PROJECT_MAP.md');
    if (!existsSync(mapPath)) return;
    try {
      const content = readFileSync(mapPath, 'utf8');
      this.lastSynthesis = {
        projectMap: content,
        decisions: '',
        summary: 'Init scan: project structure mapped from filesystem analysis.',
      };
    } catch { /* non-fatal */ }
  }

  stop() {
    if (this.interval) {
      clearInterval(this.interval);
      this.interval = null;
    }
    if (this._debounceTimer) {
      clearTimeout(this._debounceTimer);
      this._debounceTimer = null;
    }
  }

  requestSynthesis(reason = 'unknown') {
    if (reason === 'completion' || reason === 'rotation_complete') {
      this._forceNextCycle = true;
    }
    if (this._debounceTimer) {
      this._debounceReason = reason;
      return;
    }
    this._debounceReason = reason;
    this._debounceTimer = setTimeout(() => {
      const r = this._debounceReason;
      this._debounceTimer = null;
      this._debounceReason = null;
      this.cycle().catch((err) => {
        console.error(`  Journalist requestSynthesis(${r}) failed:`, err.message);
      });
    }, DEBOUNCE_MS);
  }

  async ensureFresh(maxAgeMs = 30000) {
    if (this.lastCycleAt && (Date.now() - this.lastCycleAt) < maxAgeMs) {
      return;
    }
    await this.cycle();
  }

  async cycle() {
    if (this.synthesizing) {
      console.log('  Journalist: skipping cycle (already synthesizing)');
      return;
    }

    const agents = this.daemon.registry.getAll();
    const running = agents.filter((a) => a.status === 'running');

    // Include recently completed agents (last 30 min) so their work persists
    // in the project map instead of vanishing the moment they finish
    const thirtyMinAgo = new Date(Date.now() - 30 * 60 * 1000).toISOString();
    const recentlyCompleted = agents.filter((a) =>
      a.status === 'completed' && a.lastActivity && a.lastActivity > thirtyMinAgo
      && !running.some((r) => r.id === a.id)
    );
    const activeAgents = [...running, ...recentlyCompleted];

    // Skip if no agents to synthesize
    if (activeAgents.length === 0) {
      console.log('  Journalist: skipping cycle (no active agents)');
      return;
    }

    // Smart scheduling: skip if no new log output since last cycle (unless forced by completion/rotation)
    if (this.lastCycleAt && !this._forceNextCycle && !this.hasNewActivity(activeAgents)) {
      console.log('  Journalist: skipping cycle (no new activity)');
      return;
    }

    this.synthesizing = true;
    this._forceNextCycle = false;
    this.cycleCount++;
    this.lastCycleAt = Date.now();

    try {
      // 1. Collect and filter recent logs
      const filteredLogs = this.collectFilteredLogs(activeAgents);

      // 2. Run AI synthesis (or fallback to structural summary)
      const synthesis = await this.synthesize(activeAgents, filteredLogs);

      // 3. Write outputs
      this.writeProjectMap(synthesis.projectMap);
      this.writeDecisionsLog(synthesis.decisions);
      this.writeAgentSessionLogs(activeAgents, filteredLogs);

      // Post-synthesis: extract Layer 7 memory from agent logs
      this._extractDiscoveries(filteredLogs);
      this._extractConstraints(filteredLogs);

      this.lastSynthesis = synthesis;
      this.history.push({
        cycle: this.cycleCount,
        timestamp: new Date().toISOString(),
        agentCount: activeAgents.length,
        summary: synthesis.summary,
      });
      // Keep last 50 entries
      if (this.history.length > 50) this.history = this.history.slice(-50);

      this.daemon.broadcast({
        type: 'journalist:cycle',
        data: {
          cycle: this.cycleCount,
          agentCount: activeAgents.length,
          summary: synthesis.summary,
          projectMap: synthesis.projectMap,
        },
      });
    } catch (err) {
      console.error('  Journalist cycle failed:', err.message);
    } finally {
      this.synthesizing = false;
    }
  }

  // --- Log collection & filtering ---

  hasNewActivity(agents) {
    for (const agent of agents) {
      const logPath = resolve(this.daemon.grooveDir, 'logs', `${agent.id}.log`);
      if (!existsSync(logPath)) continue;
      try {
        const size = statSync(logPath).size;
        if (size !== (this.lastLogSizes[agent.id] || 0)) return true;
      } catch { /* ignore */ }
    }
    return false;
  }

  collectFilteredLogs(agents, { since } = {}) {
    const result = {};

    for (const agent of agents) {
      const logPath = resolve(this.daemon.grooveDir, 'logs', `${agent.id}.log`);
      if (!existsSync(logPath)) {
        result[agent.id] = { agent, entries: [], explorationEntries: [] };
        continue;
      }

      try {
        const content = readFileSync(logPath, 'utf8');
        const size = Buffer.byteLength(content);
        this.lastLogSizes[agent.id] = size;

        const { entries, explorationEntries } = this.filterLog(content, agent, { since });
        result[agent.id] = { agent, entries, explorationEntries };
      } catch {
        result[agent.id] = { agent, entries: [], explorationEntries: [] };
      }
    }

    return result;
  }

  filterLog(rawLog, agent, { since } = {}) {
    // Parse stream-json lines and extract meaningful events.
    // Focus on PROGRESS (writes, edits, commands with results) not EXPLORATION (reads, greps).
    // Exploration tools are tracked separately so handoff briefs can include what was examined.
    const entries = [];
    const explorationEntries = [];
    const lines = rawLog.split('\n');
    const toolResults = new Map(); // tool_use_id -> result text

    const sinceDate = since ? new Date(since) : null;

    // First pass: collect tool results (and error flags) so we can attach them to tool calls
    const toolErrors = new Set(); // tool_use_ids that returned errors
    for (const line of lines) {
      if (!line.trim() || line.startsWith('[')) continue;
      try {
        const data = JSON.parse(line);
        if (sinceDate && data.timestamp && new Date(data.timestamp) < sinceDate) continue;
        if (data.type === 'user' && data.message?.content) {
          const content = Array.isArray(data.message.content) ? data.message.content : [];
          for (const block of content) {
            if (block.type === 'tool_result' && block.tool_use_id) {
              const text = typeof block.content === 'string' ? block.content
                : Array.isArray(block.content) ? block.content.map((c) => c.text || '').join('').slice(0, 300)
                : '';
              if (text) toolResults.set(block.tool_use_id, text);
              if (block.is_error || (typeof text === 'string' && text.includes('Error'))) {
                toolErrors.add(block.tool_use_id);
              }
            }
          }
        }
      } catch { /* skip */ }
    }

    // Second pass: extract meaningful events
    for (const line of lines) {
      if (!line.trim() || line.startsWith('[')) continue;

      try {
        const data = JSON.parse(line);
        if (sinceDate && data.timestamp && new Date(data.timestamp) < sinceDate) continue;

        // Tool use — only keep WRITES, EDITS, and COMMANDS (progress, not exploration)
        if (data.type === 'assistant' && data.message?.content) {
          const content = data.message.content;
          if (Array.isArray(content)) {
            for (const block of content) {
              if (block.type === 'tool_use') {
                const tool = block.name;

                // Exploration tools: track separately for detailed handoff briefs,
                // but also include in main entries so synthesis captures what was
                // examined. This prevents new agents from re-exploring the same files.
                if (tool === 'Read' || tool === 'Glob' || tool === 'Grep') {
                  const explorationEntry = {
                    type: 'exploration',
                    tool,
                    input: this.summarizeToolInput(tool, block.input),
                    timestamp: data.timestamp,
                  };
                  explorationEntries.push(explorationEntry);
                  entries.push(explorationEntry);
                  continue;
                }

                const entry = {
                  type: 'tool',
                  tool,
                  input: this.summarizeToolInput(tool, block.input),
                  timestamp: data.timestamp,
                };

                // Capture what was actually changed for Edit operations
                if (tool === 'Edit' && block.input) {
                  const old = (block.input.old_string || '').slice(0, 150);
                  const nw = (block.input.new_string || '').slice(0, 150);
                  if (old && nw) entry.diff = `"${old}" → "${nw}"`;
                }

                // Capture Bash command output (exit code, first line of result)
                if (tool === 'Bash' && block.id) {
                  const result = toolResults.get(block.id);
                  if (result) entry.output = result.slice(0, 200);
                }

                // Promote to error if the tool result was flagged is_error
                if (block.id && toolErrors.has(block.id)) {
                  entry.type = 'error';
                  entry.text = toolResults.get(block.id)?.slice(0, 300) || entry.input;
                }

                entries.push(entry);
              } else if (block.type === 'text' && block.text) {
                // Keep reasoning that contains decisions or conclusions.
                // Under 50 chars is noise ("Let me check...", "OK"), but 50-200
                // often contains key decisions like "Using X instead of Y".
                const text = block.text.trim();
                if (text.length > 50) {
                  entries.push({ type: 'thinking', text: text.slice(0, 2000), timestamp: data.timestamp });
                }
              }
            }
          }
        }

        // User messages — capture for constraint extraction
        if (data.type === 'user' && data.message?.content) {
          const content = data.message.content;
          if (typeof content === 'string' && content.trim().length > 10) {
            entries.push({ type: 'user', text: content.slice(0, 500), timestamp: data.timestamp });
          } else if (Array.isArray(content)) {
            for (const block of content) {
              if (block.type === 'text' && block.text && block.text.trim().length > 10) {
                entries.push({ type: 'user', text: block.text.slice(0, 500), timestamp: data.timestamp });
              }
            }
          }
        }

        // Result / completion
        if (data.type === 'result') {
          entries.push({
            type: 'result',
            text: typeof data.result === 'string' ? data.result.slice(0, 3000) : '',
            cost: data.total_cost_usd,
            turns: data.num_turns,
            duration: data.duration_ms,
          });
        }
      } catch {
        // Skip non-JSON lines entirely — transient stderr like ENOENT
        // causes degradation when agents try to "fix" phantom errors
      }
    }

    return { entries, explorationEntries };
  }

  summarizeToolInput(toolName, input) {
    if (!input) return '';
    switch (toolName) {
      case 'Write':
        return input.file_path || input.path || '';
      case 'Edit':
        return input.file_path || input.path || '';
      case 'Read':
        return input.file_path || input.path || '';
      case 'Grep':
        return `${input.pattern || ''}${input.path ? ' in ' + input.path : ''}`;
      case 'Glob':
        return input.pattern || '';
      case 'Bash':
        return (input.command || '').slice(0, 150);
      default:
        return JSON.stringify(input).slice(0, 100);
    }
  }

  // --- AI Synthesis ---

  async synthesize(agents, filteredLogs) {
    // Build synthesis prompt from filtered logs
    const prompt = this.buildSynthesisPrompt(agents, filteredLogs);

    // Try headless AI call for synthesis
    try {
      const result = await this.callHeadless(prompt);
      return this.parseSynthesisResult(result, agents);
    } catch (err) {
      // Fallback to structural summary (no AI call)
      console.error('  Journalist AI synthesis unavailable:', err.message);
      return this.buildStructuralSummary(agents, filteredLogs);
    }
  }

  buildSynthesisPrompt(agents, filteredLogs) {
    const hasWorkspaces = agents.some((a) => a.workingDir);

    const parts = [
      'You are The Journalist for GROOVE, an agent orchestration system.',
      'Analyze the following agent activity logs and produce a synthesis.',
      '',
      'Output EXACTLY this format (use these exact headers):',
      '',
      '## Project Map',
      hasWorkspaces
        ? '(What has been built/changed, organized by workspace/directory. Use ### subheadings for each workspace.)'
        : '(What has been built/changed, organized by area. Be specific about files and functions.)',
      '',
      '## Decisions',
      '(Key architectural and implementation decisions agents made, with reasoning.)',
      '',
      '## Summary',
      '(2-3 sentence overview of current progress.)',
      '',
      '---',
      '',
    ];

    // Group agents by workspace for clarity
    const grouped = this.groupByWorkspace(agents);
    let totalChars = 0;

    for (const [workspace, wsAgents] of grouped) {
      if (hasWorkspaces) {
        parts.push(`--- Workspace: ${workspace} ---`);
        parts.push('');
      }

      for (const agent of wsAgents) {
        const log = filteredLogs[agent.id];
        if (!log || log.entries.length === 0) continue;

        const dir = agent.workingDir ? `, dir: ${agent.workingDir}` : '';
        parts.push(`### Agent: ${agent.name} (${agent.role}${dir}, scope: ${agent.scope?.join(', ') || 'unrestricted'})`);

        for (const entry of log.entries.slice(-100)) {
          const line = this.formatEntry(entry);
          if (totalChars + line.length > MAX_LOG_CHARS) break;
          parts.push(line);
          totalChars += line.length;
        }
        parts.push('');
      }
    }

    return parts.join('\n');
  }

  buildRotationSynthesisPrompt(agent, entries, options = {}) {
    const dir = agent.workingDir ? `\nWorking directory: ${agent.workingDir}` : '';
    const reason = options.reason || 'manual rotation';

    const parts = [
      'You are briefing the next AI agent taking over this exact role.',
      `The previous agent (${agent.name}, role: ${agent.role}) is being rotated out.`,
      `Scope: ${agent.scope?.join(', ') || 'unrestricted'}${dir}`,
      `Rotation reason: ${reason}`,
      '',
      'Analyze the FULL session log below and produce a structured handoff brief.',
      'The next agent must be able to continue this work without repeating anything.',
      '',
      'Output EXACTLY these sections, in this priority order:',
      '',
      '## Investigation Path',
      '(Chronological narrative of what was explored and why. For each major step:',
      ' what was tried, what the result was, and whether it was ruled out or remains viable.',
      ' The next agent must know the full path taken to avoid retreading ground.)',
      '',
      '## Current State',
      '(Where things stand right now. What is the current hypothesis or approach?',
      ' What was the agent actively working on when rotated? What is the next step?)',
      '',
      '## What Was Ruled Out',
      '(Approaches, files, or theories that were investigated and eliminated.',
      ' Include WHY each was ruled out so the next agent does not retry them.)',
      '',
      '## Key Findings',
      '(Important discoveries: root causes identified, relevant code locations,',
      ' configuration details, error patterns, dependencies found. Name files,',
      ' functions, and line numbers.)',
      '',
      '## Unresolved Errors',
      '(Errors still occurring. Include exact error messages and context.)',
      '',
      '## User Messages',
      '(EVERY message the user typed, verbatim or near-verbatim. These are critical —',
      ' the user must never have to repeat themselves after a rotation. Include all',
      ' instructions, questions, corrections, and context the user provided.)',
      '',
      '## User Constraints',
      '(Explicit user directives, must/never/avoid/use instructions.)',
      '',
      '## Last 15 Tool Calls',
      '(Compact list of the most recent meaningful tool calls and outcomes.)',
      '',
      'Be specific. Name files, functions, and line numbers. Do not summarize vaguely.',
      'Preserve the investigation narrative — the next agent needs to understand the',
      'journey, not just the destination.',
      'IMPORTANT: Focus on what the user ASKED the agent to do (the original task).',
      'Do NOT include observations about unrelated code issues, potential improvements,',
      'or things the agent noticed but did not act on. The next agent must stay on task.',
      'Keep your response under 4000 characters.',
      '',
      '---',
      '',
      `### Session Log for ${agent.name} (${agent.role})`,
      '',
    ];

    let totalChars = 0;
    const cap = 40_000;
    for (const entry of entries.slice(-500)) {
      const line = this.formatEntry(entry);
      if (totalChars + line.length > cap) break;
      parts.push(line);
      totalChars += line.length;
    }

    return parts.join('\n');
  }

  formatEntry(entry) {
    switch (entry.type) {
      case 'tool': {
        let line = `- [${entry.tool}] ${entry.input}`;
        if (entry.diff) line += ` — changed: ${entry.diff}`;
        if (entry.output) line += ` → ${entry.output.split('\n')[0]}`;
        return line;
      }
      case 'error': {
        let line = `- [ERROR] ${entry.tool ? `${entry.tool}: ` : ''}${(entry.text || entry.input || '').slice(0, 300)}`;
        return line;
      }
      case 'user':
        return `- [user] ${(entry.text || '').slice(0, 300)}`;
      case 'thinking':
        return `- [thought] ${entry.text.slice(0, 300)}`;
      case 'exploration':
        return `- [explored] ${entry.tool}: ${(entry.input || '').slice(0, 200)}`;
      case 'result':
        return `- [result] ${entry.text.slice(0, 300)} (${entry.turns} turns, ${entry.duration}ms)`;
      default:
        return `- [${entry.type}] ${entry.text || ''}`;
    }
  }

  // Extract usage from stream-json stdout and record to token tracker.
  // Reserved agent IDs (__journalist__, __pm__, etc.) capture overhead
  // separately from user-facing agents. Silent no-op if provider doesn't
  // emit usage data.
  _recordHeadlessUsage(stdout, trackAs, modelId) {
    if (!this.daemon?.tokens || !stdout) return;
    const lines = stdout.split('\n');
    for (const line of lines) {
      try {
        const data = JSON.parse(line);
        if (data.type !== 'result') continue;
        const usage = data.usage;
        if (!usage) continue;
        const inputTokens = usage.input_tokens || 0;
        const outputTokens = usage.output_tokens || 0;
        const cacheReadTokens = usage.cache_read_input_tokens || 0;
        const cacheCreationTokens = usage.cache_creation_input_tokens || 0;
        const total = inputTokens + outputTokens + cacheReadTokens + cacheCreationTokens;
        if (total === 0) continue;
        this.daemon.tokens.record(trackAs, {
          tokens: total,
          inputTokens,
          outputTokens,
          cacheReadTokens,
          cacheCreationTokens,
          model: modelId,
          estimatedCostUsd: data.total_cost_usd || 0,
        });
        return;
      } catch { /* skip non-JSON lines */ }
    }
  }

  async callHeadless(prompt, { trackAs = '__journalist__' } = {}) {
    const priority = ['claude-code', 'gemini', 'codex', 'grok', 'ollama'];
    const installed = getInstalledProviders();

    for (const providerId of priority) {
      if (!installed.some((i) => i.id === providerId)) continue;

      const provider = getProvider(providerId);
      if (!provider) continue;

      const selectedModel = provider.constructor.models?.find((m) => m.tier === 'medium')
        || provider.constructor.models?.find((m) => m.tier === 'light')
        || provider.constructor.models?.[0];
      const modelId = selectedModel?.id || null;

      // Try CLI headless command first
      const headlessCmd = provider.buildHeadlessCommand(prompt, modelId);
      if (headlessCmd) {
        try {
          return await this._execHeadlessCmd(headlessCmd, trackAs, modelId, providerId);
        } catch {
          continue;
        }
      }

      // Fallback: streamChat for API-only providers (e.g. Grok)
      if (typeof provider.streamChat === 'function') {
        const apiKey = this.daemon.credentials?.getKey(providerId);
        if (!apiKey) continue;

        try {
          const text = await new Promise((resolve, reject) => {
            let collected = '';
            const ctrl = provider.streamChat(
              [{ role: 'user', content: prompt }],
              modelId,
              apiKey,
              (chunk) => { collected += chunk; },
              () => resolve(collected),
              (err) => reject(err),
            );
            if (!ctrl) reject(new Error('streamChat unavailable'));
          });

          if (text) {
            const estimatedInputTokens = Math.ceil(prompt.length / 4);
            const estimatedOutputTokens = Math.ceil(text.length / 4);
            if (this.daemon?.tokens) {
              this.daemon.tokens.record(trackAs, {
                tokens: estimatedInputTokens + estimatedOutputTokens,
                inputTokens: estimatedInputTokens,
                outputTokens: estimatedOutputTokens,
                model: modelId,
                estimatedCostUsd: 0,
              });
            }
            return text;
          }
        } catch {
          continue;
        }
      }
    }

    throw new Error('No provider available for synthesis');
  }

  _execHeadlessCmd(headlessCmd, trackAs, modelId, providerId) {
    const { command: rawCommand, args, env, stdin: stdinData } = headlessCmd;
    const command = (providerId && resolveProviderCommand(providerId)) || rawCommand;

    return new Promise((resolve, reject) => {
      if (stdinData) {
        let stdout = '';
        const proc = cpSpawn(command, args, {
          env: { ...process.env, ...env },
          cwd: this.daemon.projectDir,
          stdio: ['pipe', 'pipe', 'pipe'],
        });
        proc.on('error', (err) => reject(err));
        proc.stdin.write(stdinData);
        proc.stdin.end();
        proc.stdout.on('data', (d) => { stdout += d.toString(); });
        const timer = setTimeout(() => { proc.kill(); reject(new Error('Headless timeout')); }, 120_000);
        proc.on('exit', (code) => {
          clearTimeout(timer);
          if (code !== 0) return reject(new Error(`Headless exited with code ${code}`));
          this._recordHeadlessUsage(stdout, trackAs, modelId);
          const extracted = this._parseHeadlessOutput(stdout);
          if (extracted) return resolve(extracted);
          reject(new Error('Headless produced no usable output'));
        });
        return;
      }

      execFile(command, args, {
        env: { ...process.env, ...env },
        cwd: this.daemon.projectDir,
        maxBuffer: 1024 * 1024 * 5,
        timeout: 120_000,
      }, (err, stdout, stderr) => {
        if (err) return reject(err);
        this._recordHeadlessUsage(stdout, trackAs, modelId);
        const extracted = this._parseHeadlessOutput(stdout);
        if (extracted) return resolve(extracted);
        reject(new Error('Headless produced no usable output'));
      });
    });
  }

  _parseHeadlessOutput(stdout) {
    const lines = stdout.split('\n');
    let resultText = '';
    let assistantText = '';
    let codexText = '';
    let networkText = '';

    for (const line of lines) {
      try {
        const json = JSON.parse(line);

        // Claude/Gemini stream-json: {"type":"result","result":"..."}
        if (typeof json.result === 'string' && json.result.trim()) {
          resultText = json.result;
        }

        // Claude/Gemini assistant message: {"type":"assistant","message":{"content":[{"type":"text","text":"..."}]}}
        const msgContent = json.message?.content?.[0]?.text || json.content?.[0]?.text;
        if (msgContent && msgContent.trim()) {
          assistantText = msgContent;
        }

        // Codex --json: {"type":"item.completed","item":{"type":"agent_message","text":"..."}}
        if (json.type === 'item.completed' && json.item?.type === 'agent_message' && json.item.text?.trim()) {
          codexText = json.item.text;
        }

        // Groove Network: {"type":"done|complete|result","text":"..."}
        if ((json.type === 'done' || json.type === 'complete') && typeof json.text === 'string' && json.text.trim()) {
          networkText = json.text;
        }
      } catch { /* not json */ }
    }

    if (resultText) return resultText;
    if (codexText) return codexText;
    if (networkText) return networkText;
    if (assistantText) return assistantText;
    // Ollama / plain-text providers: raw text output (no JSON)
    const plain = stdout.trim();
    if (plain && !plain.startsWith('{') && plain.length > 20) return plain;
    return null;
  }

  parseSynthesisResult(text, agents) {
    // Parse the structured output from AI
    const sections = {
      projectMap: '',
      decisions: '',
      summary: '',
    };

    const mapMatch = text.match(/## Project Map\n([\s\S]*?)(?=## Decisions|## Summary|$)/);
    const decMatch = text.match(/## Decisions\n([\s\S]*?)(?=## Project Map|## Summary|$)/);
    const sumMatch = text.match(/## Summary\n([\s\S]*?)(?=## Project Map|## Decisions|$)/);

    sections.projectMap = this.buildProjectMapMd(
      agents,
      mapMatch ? mapMatch[1].trim() : 'No changes detected.'
    );
    sections.decisions = decMatch ? decMatch[1].trim() : '';
    sections.summary = sumMatch ? sumMatch[1].trim() : 'Synthesis cycle complete.';

    return sections;
  }

  // --- Fallback structural summary (no AI) ---

  buildStructuralSummary(agents, filteredLogs) {
    const decisions = [];
    const summaryParts = [];
    const grouped = this.groupByWorkspace(agents);
    const workspaceSections = {};

    for (const [workspace, wsAgents] of grouped) {
      const mapParts = [];

      for (const agent of wsAgents) {
        const log = filteredLogs[agent.id];
        if (!log) continue;
        const entries = log.entries;
        const tools = entries.filter((e) => e.type === 'tool');
        const errors = entries.filter((e) => e.type === 'error');
        const writes = tools.filter((t) => t.tool === 'Write' || t.tool === 'Edit');
        const reads = tools.filter((t) => t.tool === 'Read');

        mapParts.push(`### ${agent.name} (${agent.role})`);
        if (writes.length > 0) {
          mapParts.push(`Files modified:`);
          const files = [...new Set(writes.map((w) => w.input).filter(Boolean))];
          files.forEach((f) => mapParts.push(`- ${f}`));
        }
        if (reads.length > 0) {
          const files = [...new Set(reads.map((r) => r.input).filter(Boolean))];
          mapParts.push(`Files read: ${files.slice(0, 10).join(', ')}`);
        }
        if (errors.length > 0) {
          mapParts.push(`Errors: ${errors.length}`);
        }
        mapParts.push(`Activity: ${entries.length} events, ${tools.length} tool calls`);
        mapParts.push('');

        summaryParts.push(`${agent.name}: ${tools.length} tool calls, ${writes.length} writes`);

        const thoughts = entries.filter((e) => e.type === 'thinking');
        for (const t of thoughts.slice(-3)) {
          if (t.text.length > 100) {
            decisions.push(`- **${agent.name}**: ${t.text.slice(0, 200)}`);
          }
        }
      }

      workspaceSections[workspace] = mapParts.join('\n');
    }

    return {
      projectMap: this.buildProjectMapMd(agents, workspaceSections),
      decisions: decisions.join('\n'),
      summary: summaryParts.join('. ') || 'No activity.',
    };
  }

  buildProjectMapMd(agents, content) {
    const hasWorkspaces = agents.some((a) => a.workingDir);

    const lines = [
      `# GROOVE Project Map`,
      ``,
      `*Auto-generated by The Journalist. Cycle ${this.cycleCount}. Updated: ${new Date().toISOString()}*`,
      ``,
      `## Active Agents`,
      ``,
      ...agents.map((a) => {
        const dir = a.workingDir ? ` — dir: ${a.workingDir}` : '';
        return `- **${a.name}** (${a.role}) — ${a.provider}${dir} — ${a.scope?.join(', ') || 'unrestricted'} — tokens: ${a.tokensUsed}`;
      }),
      ``,
    ];

    // Content can be a string (from AI synthesis) or an object of workspace sections (from structural)
    if (typeof content === 'string') {
      lines.push(`## Activity`, ``, content);
    } else {
      // Workspace-sectioned content: { workspaceName: markdownContent }
      const entries = Object.entries(content);
      if (entries.length === 1 && entries[0][0] === 'project root') {
        // Single workspace = flat layout (backwards compat)
        lines.push(`## Activity`, ``, entries[0][1]);
      } else {
        for (const [workspace, sectionContent] of entries) {
          if (!sectionContent.trim()) continue;
          lines.push(`## ${workspace}`, ``, sectionContent);
        }
      }
    }

    return lines.join('\n');
  }

  // --- File outputs ---

  writeProjectMap(content) {
    writeFileSync(resolve(this.daemon.projectDir, 'GROOVE_PROJECT_MAP.md'), content);
  }

  writeDecisionsLog(decisions) {
    if (!decisions) return;

    const path = resolve(this.daemon.projectDir, 'GROOVE_DECISIONS.md');
    const header = `# GROOVE Decisions Log\n\n*Auto-generated by The Journalist.*\n\n`;

    let existing = '';
    if (existsSync(path)) {
      existing = readFileSync(path, 'utf8').replace(/^# GROOVE Decisions Log[\s\S]*?\n\n/, '');
    }

    // Deduplicate — skip if the new decisions are substantially similar to the most recent entry.
    // Extract the last cycle's decisions text for comparison.
    if (existing) {
      const lastEntry = existing.match(/^## Cycle[\s\S]*?\n\n([\s\S]*?)(?=\n---|\n\n\*Auto|\n## Cycle|$)/);
      if (lastEntry) {
        const lastText = lastEntry[1].trim().toLowerCase().replace(/\s+/g, ' ');
        const newText = decisions.trim().toLowerCase().replace(/\s+/g, ' ');
        // If >60% of the new text appears in the last entry, skip (near-duplicate)
        const newWords = newText.split(' ').filter((w) => w.length > 3);
        const overlap = newWords.filter((w) => lastText.includes(w)).length;
        if (newWords.length > 0 && overlap / newWords.length > 0.6) return;
      }
    }

    const entry = `## Cycle ${this.cycleCount} — ${new Date().toISOString()}\n\n${decisions}\n\n`;

    // Keep last 20 entries max to prevent unbounded growth
    const entries = (entry + existing).split(/(?=^## Cycle)/m).slice(0, 20).join('');
    writeFileSync(path, header + entries);
  }

  writeAgentSessionLogs(agents, filteredLogs) {
    const logsDir = resolve(this.daemon.projectDir, 'GROOVE_AGENT_LOGS');
    mkdirSync(logsDir, { recursive: true });

    const dateStr = new Date().toISOString().split('T')[0];

    for (const [agentId, { agent, entries }] of Object.entries(filteredLogs)) {
      if (entries.length === 0) continue;

      const agentDir = resolve(logsDir, agent.id);
      mkdirSync(agentDir, { recursive: true });

      const logPath = resolve(agentDir, `${dateStr}-session.md`);
      const content = [
        `# ${agent.name} — Session Log`,
        ``,
        `*Updated: ${new Date().toISOString()}*`,
        ``,
        `- Role: ${agent.role}`,
        `- Provider: ${agent.provider}`,
        `- Scope: ${agent.scope?.join(', ') || 'unrestricted'}`,
        `- Tokens: ${agent.tokensUsed}`,
        ``,
        `## Activity`,
        ``,
        ...entries.slice(-100).map((e) => this.formatEntry(e)),
      ].join('\n');

      writeFileSync(logPath, content);
    }
  }

  // --- Handoff Brief for Context Rotation ---

  async generateHandoffBrief(agent, options = {}) {
    const filteredLogs = this.collectFilteredLogs([agent], { since: agent.spawnedAt });
    const agentLog = filteredLogs[agent.id];
    const entries = agentLog?.entries || [];

    // Layer 7 memory: discoveries (inline, not pointer — agents lose context with pointers), constraints, specializations
    const discoveries = this.daemon.memory?.getDiscoveriesMarkdown(agent.role, 10, 1500, agent.scope, agent.teamId) || '';
    const constraints = this.daemon.memory?.getConstraintsMarkdown(2000) || '';
    const specialization = this.daemon.memory?.getSpecialization(agent.id);
    const specLine = specialization?.avgQualityScore != null
      ? `- Quality profile: ${specialization.avgQualityScore}/100 across ${specialization.sessionCount} sessions`
      : '';

    const recentChain = this.daemon.memory?.getRecentHandoffMarkdown(agent.role, 3, 3000, agent.workingDir, agent.teamId) || '';

    // User messages from the session log — these are the actual things the user typed.
    // They must always be preserved: if a user said it, the next agent needs to see it.
    const userMessages = entries
      .filter((e) => e.type === 'user' && e.text)
      .map((e) => `- "${e.text.slice(0, 500)}"`)
      .join('\n');

    const agentFeedback = this.getUserFeedback(agent.id).slice(-5);
    const conversationSummary = agentFeedback.length > 0
      ? agentFeedback.map((fb) => `- "${fb.message}"`).join('\n')
      : '';

    const recentTools = entries
      .filter((e) => e.type === 'tool' || e.type === 'error')
      .slice(-15)
      .map((e) => `- ${e.type === 'error' ? 'ERROR ' : ''}${e.tool}: ${(e.input || e.text || '').slice(0, 200)}`)
      .join('\n');

    // Try AI-synthesized session summary — but only if the session log has
    // meaningful entries. With an empty/minimal log the headless Claude sees
    // repo-wide git status (from its own project context) and fills the brief
    // with unrelated changes from other teams, leaking cross-team state.
    const meaningfulEntries = entries.filter((e) => e.type === 'tool' || e.type === 'error' || e.type === 'user' || e.type === 'result');
    let sessionSummary = '';
    let needsFallback = meaningfulEntries.length < 3;

    if (!needsFallback) {
      try {
        const prompt = this.buildRotationSynthesisPrompt(agent, entries, options);
        sessionSummary = await this.callHeadless(prompt, { trackAs: '__rotation__' });
      } catch {
        needsFallback = true;
      }
    }

    if (needsFallback) {
      const errorSummary = entries
        .filter((e) => e.type === 'error')
        .map((e) => `- ${e.text}`)
        .slice(-10)
        .join('\n');

      const resultSummary = entries
        .filter((e) => e.type === 'result')
        .map((e) => e.text)
        .slice(-3)
        .join('\n');

      const fileChanges = {};
      for (const e of entries.filter((e) => e.type === 'tool' && (e.tool === 'Edit' || e.tool === 'Write'))) {
        const file = e.input || 'unknown';
        if (!fileChanges[file]) fileChanges[file] = [];
        if (e.diff) fileChanges[file].push(e.diff);
        else fileChanges[file].push(e.tool === 'Write' ? 'created' : 'modified');
      }
      const fileChangesSummary = Object.entries(fileChanges)
        .map(([file, changes]) => `- **${file}**: ${changes.slice(0, 3).join('; ')}`)
        .slice(0, 20)
        .join('\n');

      const fallbackRecentTools = entries
        .filter((e) => e.type === 'tool' || e.type === 'error')
        .slice(-15)
        .map((e) => `- ${e.type === 'error' ? 'ERROR ' : ''}${e.tool}: ${(e.input || '').slice(0, 200)}`)
        .join('\n');

      const thinkingEntries = entries
        .filter((e) => e.type === 'thinking' && e.text && e.text.length > 80)
        .slice(-10)
        .map((e) => `- ${e.text.slice(0, 400)}`)
        .join('\n');

      const fallbackParts = [];
      if (thinkingEntries) fallbackParts.push(`## Investigation Path\n\n${thinkingEntries}`);
      if (errorSummary) fallbackParts.push(`## Unresolved Errors\n\n${errorSummary}`);
      if (fallbackRecentTools) fallbackParts.push(`## Last 15 Tool Calls\n\n${fallbackRecentTools}`);
      if (fileChangesSummary) fallbackParts.push(`## Files Modified\n\n${fileChangesSummary}`);
      if (resultSummary) fallbackParts.push(`## Accomplishments\n\n${resultSummary}`);
      sessionSummary = fallbackParts.join('\n\n');
    }

    // Cap Original Task to 1000 chars — task descriptions for debugging can be long
    const originalTask = agent.prompt ? agent.prompt.slice(0, 1000) + (agent.prompt.length > 1000 ? '…' : '') : '';

    // Combine user messages from session log and feedback API — never drop these
    const allUserMessages = [userMessages, conversationSummary].filter(Boolean).join('\n');

    let brief = [
      `# Handoff Brief — ${agent.name} (${agent.role})`,
      ``,
      `Role: ${agent.role} | Scope: ${agent.scope?.join(', ') || 'unrestricted'} | Provider: ${agent.provider}`,
      agent.workingDir ? `Working directory: ${agent.workingDir}` : '',
      `Rotation: ${options.reason || 'manual'}${options.qualityScore ? ` (quality: ${options.qualityScore}/100)` : ''} | Tokens: ${agent.tokensUsed}`,
      specLine,
      ``,
      // Priority order: session summary first, then user messages (never drop —
      // if the user typed it, the next agent must see it), then constraints,
      // then discoveries, then tools. Most critical context survives truncation.
      sessionSummary ? `## Session Summary\n\n${sessionSummary}\n` : '',
      allUserMessages ? `## User Messages (do not ask user to repeat these)\n\n${allUserMessages}\n` : '',
      constraints ? `## Project Constraints (must follow)\n\n${constraints}\n` : '',
      discoveries ? `## Known Issues & Fixes\n\n${discoveries}\n` : '',
      recentTools ? `## Last 15 Tool Calls\n\n${recentTools}\n` : '',
      recentChain ? `## Rotation History\n\n${recentChain}\n` : '',
      originalTask ? `## Original Task\n\n${originalTask}\n` : '',
      ``,
      agent.role === 'planner' ? 'CRITICAL: You are a PLANNING ONLY agent. Do NOT implement code. Route all work to your team via .groove/recommended-team.json.\n' : '',
      `## Instructions`,
      ``,
      `Continue and finish the in-progress task — deliver the output. Stay focused on that specific task only.`,
      `- Do NOT explore the codebase looking for other things to fix or improve`,
      `- Do NOT start new work outside the original task scope`,
      `- Do NOT act on TODO comments, code quality issues, or improvements you notice in passing`,
      `- If the task is already complete, report what was accomplished and STOP — await new instructions from the user`,
    ].filter(Boolean).join('\n');

    // Hard cap: 16000 chars — investigation context needs room to preserve the full narrative
    if (brief.length > 16000) {
      brief = brief.slice(0, 15950) + '\n\n[Brief truncated — see session logs for full context]';
    }

    return brief;
  }

  // --- Conversation Thread Extraction (for idle resume) ---

  /**
   * Extract the actual user↔assistant conversation from stream-json logs.
   * Returns the dialogue in chronological order — user messages interleaved
   * with Claude's text responses. This preserves the "why" context that
   * handoff briefs lose through summarization.
   *
   * Budget: keeps recent turns verbatim, summarizes oldest if over maxChars.
   */
  extractConversationThread(agent, { maxChars = 60000 } = {}) {
    const logPath = resolve(this.daemon.grooveDir, 'logs', `${agent.id}.log`);
    if (!existsSync(logPath)) return null;

    let content;
    try {
      content = readFileSync(logPath, 'utf8');
    } catch { return null; }

    const lines = content.split('\n');
    const turns = []; // { role: 'user'|'assistant', text, timestamp }

    for (const line of lines) {
      if (!line.trim() || line.startsWith('[')) continue;
      try {
        const data = JSON.parse(line);

        // User messages
        if (data.type === 'user' && data.message?.content) {
          const msgContent = data.message.content;
          let text = '';
          if (typeof msgContent === 'string') {
            text = msgContent;
          } else if (Array.isArray(msgContent)) {
            // Extract text blocks, skip tool_result blocks (noise)
            text = msgContent
              .filter((b) => b.type === 'text' && b.text)
              .map((b) => b.text)
              .join('\n');
          }
          if (text.trim().length > 5) {
            turns.push({ role: 'user', text: text.trim(), timestamp: data.timestamp });
          }
        }

        // Assistant text responses (what Claude said — the reasoning/explanations)
        if (data.type === 'assistant' && data.message?.content) {
          const blocks = Array.isArray(data.message.content) ? data.message.content : [];
          const textParts = blocks
            .filter((b) => b.type === 'text' && b.text && b.text.trim().length > 20)
            .map((b) => b.text.trim());
          if (textParts.length > 0) {
            turns.push({ role: 'assistant', text: textParts.join('\n'), timestamp: data.timestamp });
          }
        }
      } catch { /* skip non-JSON */ }
    }

    if (turns.length === 0) return null;

    // Deduplicate consecutive same-role turns (merge them)
    const merged = [];
    for (const turn of turns) {
      const last = merged[merged.length - 1];
      if (last && last.role === turn.role) {
        last.text += '\n' + turn.text;
      } else {
        merged.push({ ...turn });
      }
    }

    // Build the thread — keep recent turns verbatim, truncate old ones if over budget
    let thread = '';
    const formatted = merged.map((t) => {
      const label = t.role === 'user' ? 'USER' : 'CLAUDE';
      return `[${label}]:\n${t.text}`;
    });

    // Start from the end (most recent) and work backwards to fill budget
    const recentFirst = [...formatted].reverse();
    const kept = [];
    let totalLen = 0;

    for (const entry of recentFirst) {
      if (totalLen + entry.length > maxChars) {
        // Truncate this entry to fit remaining budget
        const remaining = maxChars - totalLen;
        if (remaining > 200) {
          kept.push(entry.slice(0, remaining) + '\n[...truncated]');
        }
        break;
      }
      kept.push(entry);
      totalLen += entry.length;
    }

    // Reverse back to chronological order
    kept.reverse();
    thread = kept.join('\n\n---\n\n');

    return thread;
  }

  /**
   * Build a full context-resume prompt that preserves the conversation
   * thread so a fresh agent picks up where the previous session left off.
   */
  buildConversationResumePrompt(agent, userMessage, { isRotation = false, reason } = {}) {
    const thread = this.extractConversationThread(agent);
    if (!thread) return null;

    const constraints = this.daemon.memory?.getConstraintsMarkdown(2000) || '';
    const discoveries = this.daemon.memory?.getDiscoveriesMarkdown(agent.role, 5, 1000, agent.scope, agent.teamId) || '';

    // Extract the user's original task from the conversation — the first substantial
    // user message is almost always the task assignment. This anchors the new agent.
    const originalTask = this._extractOriginalTask(thread);

    // Rotation and idle-resume need very different framing. During rotation the agent
    // has no new user message — it must continue the exact in-progress task without
    // drifting. During idle-resume the user explicitly sent a message to continue.
    const isIdleResume = !isRotation && userMessage && userMessage.trim().length > 0;

    const taskFocusBlock = isRotation ? [
      `## CRITICAL: Task Focus`,
      ``,
      `You were auto-rotated (reason: ${reason || 'context_management'}) — this is a routine context refresh, NOT a new assignment.`,
      originalTask ? `Your task: ${originalTask}` : '',
      ``,
      `Rules:`,
      `- Continue ONLY the task described in the conversation below`,
      `- Do NOT explore the codebase looking for other things to fix or improve`,
      `- Do NOT start new work that was not part of the original task`,
      `- Do NOT act on TODO comments, code quality issues, or improvements you notice in passing`,
      `- If the task is complete, report what was done and STOP — await new instructions from the user`,
      `- If the task is in progress, pick up exactly where the previous session left off`,
      ``,
    ] : [];

    let prompt = [
      `# Session Context Resume`,
      ``,
      isRotation
        ? `You are continuing a session after an automatic context rotation. Your context was refreshed but your task has NOT changed. The conversation below is your previous session — continue the same work.`
        : `You are continuing a session that went idle. Below is the full conversation from your previous session — your actual exchanges with the user. Pick up exactly where you left off. The user's new message follows at the end.`,
      ``,
      `Role: ${agent.role} | Provider: ${agent.provider} | Scope: ${agent.scope?.join(', ') || 'unrestricted'}`,
      agent.workingDir ? `Working directory: ${agent.workingDir}` : '',
      ``,
      ...taskFocusBlock,
      constraints ? `## Project Constraints\n\n${constraints}\n` : '',
      discoveries ? `## Known Issues & Fixes\n\n${discoveries}\n` : '',
      `## Previous Conversation\n\n${thread}`,
      ``,
      `---`,
      ``,
      isIdleResume ? `## New Message From User\n\n${userMessage}` : '',
      ``,
      isRotation
        ? `Continue the in-progress task from the conversation above. Stay focused on that task only. Do not ask the user to repeat anything. If the task was already completed, state that and wait for new instructions.`
        : `Continue seamlessly from the conversation above. You have the full context of what was discussed, what was tried, what worked and what didn't. Do not ask the user to repeat anything.`,
    ].filter(Boolean).join('\n');

    // Hard cap at 80K chars (~20K tokens) to leave plenty of room in context window
    if (prompt.length > 80000) {
      // Re-extract with smaller budget and rebuild
      const smallerThread = this.extractConversationThread(agent, { maxChars: 40000 });
      if (smallerThread) {
        prompt = [
          `# Session Context Resume`,
          ``,
          isRotation
            ? `You are continuing after an automatic context rotation. Your task has NOT changed.`
            : `You are continuing a session that went idle (older turns summarized to fit). Pick up exactly where you left off.`,
          ``,
          `Role: ${agent.role} | Scope: ${agent.scope?.join(', ') || 'unrestricted'}`,
          agent.workingDir ? `Working directory: ${agent.workingDir}` : '',
          ``,
          ...taskFocusBlock,
          constraints ? `## Project Constraints\n\n${constraints}\n` : '',
          `## Previous Conversation\n\n${smallerThread}`,
          ``,
          `---`,
          ``,
          isIdleResume ? `## New Message From User\n\n${userMessage}` : '',
          ``,
          isRotation
            ? `Continue the in-progress task only. Do not explore or start new work. If done, state that and wait.`
            : `Continue seamlessly. Do not ask the user to repeat anything.`,
        ].filter(Boolean).join('\n');
      }
    }

    return prompt;
  }

  _extractOriginalTask(thread) {
    // Find the first substantial USER message in the thread — that's the task.
    const match = thread.match(/\[USER\]:\n([\s\S]*?)(?=\n\n---|\n\[CLAUDE\]:|$)/);
    if (!match) return '';
    const firstMsg = match[1].trim();
    if (firstMsg.length < 10) return '';
    return firstMsg.length > 500 ? firstMsg.slice(0, 500) + '...' : firstMsg;
  }

  // --- Workspace Grouping ---

  /**
   * Group agents by workingDir. Returns a Map of workspace → agents[].
   * Agents with no workingDir go under "project root".
   */
  groupByWorkspace(agents) {
    const groups = new Map();
    for (const agent of agents) {
      const key = agent.workingDir || 'project root';
      if (!groups.has(key)) groups.set(key, []);
      groups.get(key).push(agent);
    }
    return groups;
  }

  /**
   * Extract the workspace-specific section from a project map for handoff briefs.
   * Returns the full map if no workspace match or no workspace sections.
   */
  extractWorkspaceSection(projectMap, workingDir) {
    if (!workingDir || !projectMap) return projectMap;

    // Try to find a section header matching this workspace
    // Looks for "## packages/frontend" or "## workspace-name" patterns
    const sectionPattern = new RegExp(
      `^## ${workingDir.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}\\b[^\\n]*\\n([\\s\\S]*?)(?=^## |$)`,
      'm'
    );
    const match = projectMap.match(sectionPattern);
    if (match) {
      // Include the agents header + the matched workspace section
      const agentsSection = projectMap.match(/^# GROOVE Project Map[\s\S]*?(?=^## (?!Active))/m);
      const header = agentsSection ? agentsSection[0] : '';
      return header + `## ${workingDir}\n` + match[1];
    }

    // No workspace section found — return full map (truncated)
    return projectMap;
  }

  // --- Agent File Tracking ---

  /**
   * Extract files created/modified by an agent from its raw logs.
   * Used by the Introducer to tell new agents what their teammates built.
   */
  getAgentFiles(agent) {
    const logPath = resolve(this.daemon.grooveDir, 'logs', `${agent.id}.log`);
    if (!existsSync(logPath)) return [];

    try {
      const content = readFileSync(logPath, 'utf8');
      const files = new Set();

      for (const line of content.split('\n')) {
        if (!line.trim() || line.startsWith('[')) continue;
        try {
          const data = JSON.parse(line);
          if (data.type === 'assistant' && Array.isArray(data.message?.content)) {
            for (const block of data.message.content) {
              if (block.type === 'tool_use' && (block.name === 'Write' || block.name === 'Edit')) {
                const fp = block.input?.file_path || block.input?.path;
                if (fp) {
                  // Store relative to project dir for readability
                  const projDir = this.daemon.projectDir;
                  const rel = fp.startsWith(projDir) ? fp.slice(projDir.length + 1) : fp;
                  files.add(rel);
                }
              }
            }
          }
        } catch { /* skip non-JSON */ }
      }

      return [...files];
    } catch {
      return [];
    }
  }

  /**
   * Get the final result/output text from an agent's logs.
   * Used to capture planner conclusions, build summaries, etc.
   */
  getAgentResult(agent) {
    const logPath = resolve(this.daemon.grooveDir, 'logs', `${agent.id}.log`);
    if (!existsSync(logPath)) return '';

    try {
      const content = readFileSync(logPath, 'utf8');
      let lastResult = '';

      for (const line of content.split('\n')) {
        try {
          const data = JSON.parse(line);
          if (data.type === 'result' && typeof data.result === 'string') {
            lastResult = data.result;
          }
        } catch { /* skip */ }
      }

      return lastResult.slice(0, 5000);
    } catch {
      return '';
    }
  }

  // --- User Feedback Tracking ---

  /**
   * Record user feedback/messages sent to agents.
   * This gets included in the project map and handoff briefs so future
   * agents know what the user said about previous work.
   */
  recordUserFeedback(agent, message) {
    if (!this._userFeedback) this._loadFeedback();
    if (!this._userFeedback[agent.id]) this._userFeedback[agent.id] = [];
    this._userFeedback[agent.id].push({
      agentName: agent.name,
      role: agent.role,
      message: message.slice(0, 500),
      timestamp: new Date().toISOString(),
    });
    // Keep last 20 per agent
    if (this._userFeedback[agent.id].length > 20) {
      this._userFeedback[agent.id] = this._userFeedback[agent.id].slice(-20);
    }
    this._saveFeedback();
  }

  _loadFeedback() {
    const p = resolve(this.daemon.grooveDir, 'user-feedback.json');
    try {
      if (existsSync(p)) this._userFeedback = JSON.parse(readFileSync(p, 'utf8'));
      else this._userFeedback = {};
    } catch { this._userFeedback = {}; }
  }

  _saveFeedback() {
    try {
      writeFileSync(resolve(this.daemon.grooveDir, 'user-feedback.json'), JSON.stringify(this._userFeedback, null, 2));
    } catch { /* non-fatal */ }
  }

  /**
   * Get user feedback for an agent (or all agents in a team).
   * Used by the introducer to give agents context about previous attempts.
   */
  getUserFeedback(agentOrTeamId) {
    if (!this._userFeedback) this._loadFeedback();
    if (!this._userFeedback) return [];
    if (agentOrTeamId) {
      return this._userFeedback[agentOrTeamId] || [];
    }
    // Only return all feedback when explicitly called with no argument
    const all = [];
    for (const [, entries] of Object.entries(this._userFeedback)) {
      all.push(...entries);
    }
    return all.sort((a, b) => a.timestamp.localeCompare(b.timestamp)).slice(-30);
  }

  // --- Layer 7 Memory Extraction ---

  _extractDiscoveries(filteredLogs) {
    if (!this.daemon.memory) return;

    try {
      for (const [agentId, data] of Object.entries(filteredLogs)) {
        const { agent, entries } = data;
        if (!entries || entries.length === 0) continue;

        for (let i = 0; i < entries.length - 1; i++) {
          const entry = entries[i];
          if (entry.type !== 'error') continue;

          const trigger = (entry.text || '').trim();
          if (trigger.length < 20) continue;

          for (let j = i + 1; j < Math.min(i + 6, entries.length); j++) {
            const next = entries[j];
            if (next.type !== 'tool' || (next.tool !== 'Edit' && next.tool !== 'Write')) continue;
            const fix = (next.input || '').trim();
            if (fix.length < 10) continue;

            this.daemon.memory.addDiscovery({
              agentId: agent.id,
              role: agent.role,
              teamId: agent.teamId || null,
              trigger: trigger.slice(0, 300),
              fix: fix.slice(0, 500),
              outcome: 'success',
            });
            break;
          }
        }
      }
    } catch { /* Memory extraction must never break journalist cycle */ }
  }

  _extractConstraints(filteredLogs) {
    if (!this.daemon.memory) return;

    const directivePattern = /\b(don't|do not|stop|must|always|never|use|avoid|instead|please don't|do NOT)\b/i;

    try {
      for (const [, data] of Object.entries(filteredLogs)) {
        const { entries } = data;
        if (!entries || entries.length === 0) continue;

        for (const entry of entries) {
          if (entry.type !== 'user' && entry.source !== 'user') continue;
          const text = (entry.text || entry.content || '').trim();
          if (text.length < 10 || text.length > 500) continue;
          if (!directivePattern.test(text)) continue;

          this.daemon.memory.addConstraint({
            text: text.slice(0, 500),
            category: 'user-directive',
          });
        }
      }
    } catch { /* Memory extraction must never break journalist cycle */ }
  }

  // --- Accessors ---

  getLastSynthesis() {
    return this.lastSynthesis;
  }

  getHistory() {
    return this.history;
  }

  getStatus() {
    return {
      running: !!this.interval,
      cycleCount: this.cycleCount,
      lastCycleAt: this.lastCycleAt,
      synthesizing: this.synthesizing,
    };
  }
}
