// GROOVE — QC Supervisor + Approval System
// FSL-1.1-Apache-2.0 — see LICENSE

import { writeFileSync, readFileSync, existsSync } from 'fs';
import { resolve } from 'path';

const QC_AUTO_SPAWN_THRESHOLD = 4; // Auto-spawn QC when this many agents running

export class Supervisor {
  constructor(daemon) {
    this.daemon = daemon;
    this.pendingApprovals = new Map();
    this.resolvedApprovals = [];
    this.counter = 0;
    this.qcActive = false;
    this.conflicts = [];
    this._conflictWriteTimer = null;
  }

  // --- Approval System ---

  requestApproval(agentId, action, retryPayload = null) {
    const id = `approval-${Date.now()}-${++this.counter}`;
    const agent = this.daemon.registry?.get(agentId);

    const approval = {
      id,
      agentId,
      agentName: agent?.name || agentId,
      action,
      status: 'pending',
      requestedAt: new Date().toISOString(),
    };
    if (retryPayload) approval.retryPayload = retryPayload;

    this.pendingApprovals.set(id, approval);
    this.daemon.broadcast({ type: 'approval:request', data: approval });
    return approval;
  }

  approve(approvalId) {
    const approval = this.pendingApprovals.get(approvalId);
    if (!approval) return null;

    approval.status = 'approved';
    approval.resolvedAt = new Date().toISOString();
    this.pendingApprovals.delete(approvalId);
    this.resolvedApprovals.push(approval);
    if (this.resolvedApprovals.length > 200) this.resolvedApprovals = this.resolvedApprovals.slice(-200);

    this.daemon.broadcast({ type: 'approval:resolved', data: approval });
    return approval;
  }

  reject(approvalId, reason) {
    const approval = this.pendingApprovals.get(approvalId);
    if (!approval) return null;

    approval.status = 'rejected';
    approval.reason = reason || '';
    approval.resolvedAt = new Date().toISOString();
    this.pendingApprovals.delete(approvalId);
    this.resolvedApprovals.push(approval);
    if (this.resolvedApprovals.length > 200) this.resolvedApprovals = this.resolvedApprovals.slice(-200);

    this.daemon.broadcast({ type: 'approval:resolved', data: approval });
    return approval;
  }

  getPending() {
    return Array.from(this.pendingApprovals.values());
  }

  getResolved() {
    return this.resolvedApprovals;
  }

  getApproval(id) {
    return this.pendingApprovals.get(id) || this.resolvedApprovals.find((a) => a.id === id) || null;
  }

  // --- Conflict Detection ---

  recordConflict(agentId, filePath, ownerId) {
    const agent = this.daemon.registry?.get(agentId);
    const owner = this.daemon.registry?.get(ownerId);

    const conflict = {
      timestamp: new Date().toISOString(),
      agentId,
      agentName: agent?.name || agentId,
      filePath,
      ownerId,
      ownerName: owner?.name || ownerId,
    };

    this.conflicts.push(conflict);
    if (this.conflicts.length > 200) this.conflicts = this.conflicts.slice(-200);

    // Track in token savings
    this.daemon.tokens?.recordConflictPrevented();

    // Create an approval for the out-of-scope access
    this.requestApproval(agentId, {
      type: 'scope_violation',
      description: `${agent?.name || agentId} tried to modify ${filePath} (owned by ${owner?.name || ownerId})`,
      filePath,
      ownerId,
    });

    // Update GROOVE_CONFLICTS.md (debounced — at most once per 5s)
    this._debouncedWriteConflicts();

    this.daemon.broadcast({
      type: 'conflict:detected',
      data: conflict,
    });

    return conflict;
  }

  getConflicts() {
    return this.conflicts;
  }

  _debouncedWriteConflicts() {
    if (this._conflictWriteTimer) return;
    this._conflictWriteTimer = setTimeout(() => {
      this._conflictWriteTimer = null;
      this.writeConflictsFile();
    }, 5000);
  }

  writeConflictsFile() {
    if (!this.daemon.projectDir) return;
    if (this.conflicts.length === 0) return;

    const lines = [
      `# GROOVE Conflicts Log`,
      ``,
      `*Auto-generated by QC Supervisor.*`,
      ``,
      `| Time | Agent | Attempted File | Owner | Status |`,
      `|------|-------|---------------|-------|--------|`,
    ];

    for (const c of this.conflicts.slice(-50)) {
      const time = new Date(c.timestamp).toLocaleTimeString();
      lines.push(`| ${time} | ${c.agentName} | ${c.filePath} | ${c.ownerName} | blocked |`);
    }

    writeFileSync(resolve(this.daemon.projectDir, 'GROOVE_CONFLICTS.md'), lines.join('\n'));
  }

  // --- QC Auto-spawn ---

  checkQcThreshold() {
    if (this.qcActive) return false;

    const running = this.daemon.registry?.getAll().filter(
      (a) => a.status === 'running' && a.role !== 'qc'
    ) || [];

    if (running.length >= QC_AUTO_SPAWN_THRESHOLD) {
      this.qcActive = true;
      this.daemon.broadcast({
        type: 'qc:activated',
        agentCount: running.length,
      });
      return true;
    }

    return false;
  }

  isQcActive() {
    return this.qcActive;
  }

  getStatus() {
    return {
      qcActive: this.qcActive,
      pendingApprovals: this.getPending().length,
      resolvedApprovals: this.resolvedApprovals.length,
      conflicts: this.conflicts.length,
    };
  }
}
